// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

const FALLBACK_SUPABASE_URL = 'http://localhost:54321';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'local-dev-anon-key';

const isValidHttpUrl = (value: string | undefined) => {
  if (!value) return false;
  try {
    const parsed = new URL(value);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
};

const effectiveSupabaseUrl = isValidHttpUrl(SUPABASE_URL) ? SUPABASE_URL : FALLBACK_SUPABASE_URL;
const effectiveSupabaseKey = SUPABASE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (!isValidHttpUrl(SUPABASE_URL) || !SUPABASE_KEY) {
  console.warn(
    'Missing or invalid Supabase env values. Expected VITE_SUPABASE_URL and either VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY. Using local fallback values.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  effectiveSupabaseUrl,
  effectiveSupabaseKey,
  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
}
);